## NEUTRALIZED ### # This file is a template, and might need editing before it works on your project.
## NEUTRALIZED ### image: python:2.7

## NEUTRALIZED ### before_script:
## NEUTRALIZED ###   - python -V                                   # Print out python version for debugging

## NEUTRALIZED ### test:
## NEUTRALIZED ###   script:
## NEUTRALIZED ###   #- python setup.py test
## NEUTRALIZED ###   - pip install tox flake8 hacking pycodestyle pylint ClusterShell # you can also use tox
## NEUTRALIZED ###   #- tox -e py27,
## NEUTRALIZED ###   - git checkout dist
## NEUTRALIZED ###   - git pull
## NEUTRALIZED ###   - flake8 --exit-zero
## NEUTRALIZED ###   - pylint decimate.py env.py engine.py